name: Tests
on: push
jobs:
    test-node-js:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [18]
        name: Node.js v${{ matrix.node-version }}
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - name: Install dependencies
              run: make node_modules
            - name: Install CDT
              run: |
                  wget https://github.com/AntelopeIO/cdt/actions/runs/7549923279/artifacts/1173981216
                  sudo apt install unzip
                  unzip cdt_ubuntu_package_amd64.zip
                  sudo apt install ./cdt_4.0.1-1_amd64.deb
            - name: Run checks
              run: make check
            - name: Run build
              run: make build
            - name: Run tests
              run: make test
